# Generated by Django 4.2.6 on 2023-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('time_purchased', models.DateTimeField(auto_now_add=True)),
                ('expense_type', models.CharField(choices=[('Transport', 'Transport'), ('Food', 'Food'), ('Leisure', 'Leisure'), ('Electronics', 'Electronics'), ('House&Renovation', 'House&Renovation'), ('Cloths', 'Cloths'), ('Medicin', 'Medicin')], max_length=20)),
            ],
        ),
    ]
